const foodDatabase = [
    // Fruits
    { id: 1, name: "Apple", category: "fruits", calories: 52, protein: 0.3, carbs: 14, fat: 0.2, servingSize: 100, servingUnit: "g" },
    { id: 2, name: "Banana", category: "fruits", calories: 89, protein: 1.1, carbs: 23, fat: 0.3, servingSize: 100, servingUnit: "g" },
    { id: 3, name: "Orange", category: "fruits", calories: 47, protein: 0.9, carbs: 12, fat: 0.1, servingSize: 100, servingUnit: "g" },
    { id: 4, name: "Grapes", category: "fruits", calories: 69, protein: 0.7, carbs: 18, fat: 0.2, servingSize: 100, servingUnit: "g" },
    { id: 5, name: "Strawberries", category: "fruits", calories: 32, protein: 0.7, carbs: 7.7, fat: 0.3, servingSize: 100, servingUnit: "g" },
    { id: 6, name: "Blueberries", category: "fruits", calories: 57, protein: 0.7, carbs: 14, fat: 0.3, servingSize: 100, servingUnit: "g" },
    { id: 7, name: "Mango", category: "fruits", calories: 60, protein: 0.8, carbs: 15, fat: 0.4, servingSize: 100, servingUnit: "g" },
    { id: 8, name: "Pineapple", category: "fruits", calories: 50, protein: 0.5, carbs: 13, fat: 0.1, servingSize: 100, servingUnit: "g" },
    { id: 9, name: "Watermelon", category: "fruits", calories: 30, protein: 0.6, carbs: 7.6, fat: 0.2, servingSize: 100, servingUnit: "g" },
    { id: 10, name: "Peach", category: "fruits", calories: 39, protein: 0.9, carbs: 9.5, fat: 0.3, servingSize: 100, servingUnit: "g" },
    { id: 11, name: "Pear", category: "fruits", calories: 57, protein: 0.4, carbs: 15, fat: 0.1, servingSize: 100, servingUnit: "g" },
    { id: 12, name: "Cherries", category: "fruits", calories: 50, protein: 1, carbs: 12, fat: 0.3, servingSize: 100, servingUnit: "g" },
    { id: 163, name: "Papaya", category: "fruits", calories: 43, protein: 0.5, carbs: 11, fat: 0.3, servingSize: 100, servingUnit: "g" },
    { id: 164, name: "Kiwi", category: "fruits", calories: 61, protein: 1.1, carbs: 14, fat: 0.5, servingSize: 100, servingUnit: "g" },
    { id: 165, name: "Pomegranate", category: "fruits", calories: 83, protein: 1.7, carbs: 19, fat: 1.2, servingSize: 100, servingUnit: "g" },
    { id: 166, name: "Guava", category: "fruits", calories: 68, protein: 2.6, carbs: 14, fat: 1, servingSize: 100, servingUnit: "g" },
    { id: 167, name: "Lychee", category: "fruits", calories: 66, protein: 0.8, carbs: 17, fat: 0.4, servingSize: 100, servingUnit: "g" },
    { id: 168, name: "Dragon Fruit", category: "fruits", calories: 60, protein: 1.2, carbs: 13, fat: 0, servingSize: 100, servingUnit: "g" },
    { id: 169, name: "Passion Fruit", category: "fruits", calories: 97, protein: 2.2, carbs: 23, fat: 0.7, servingSize: 100, servingUnit: "g" },
    { id: 170, name: "Avocado", category: "fruits", calories: 160, protein: 2, carbs: 9, fat: 15, servingSize: 100, servingUnit: "g" },
    { id: 171, name: "Fig", category: "fruits", calories: 74, protein: 0.8, carbs: 19, fat: 0.3, servingSize: 100, servingUnit: "g" },
    { id: 172, name: "Plum", category: "fruits", calories: 46, protein: 0.7, carbs: 11, fat: 0.3, servingSize: 100, servingUnit: "g" },
    { id: 173, name: "Apricot", category: "fruits", calories: 48, protein: 1.4, carbs: 11, fat: 0.4, servingSize: 100, servingUnit: "g" },
    { id: 174, name: "Nectarine", category: "fruits", calories: 44, protein: 1.1, carbs: 11, fat: 0.3, servingSize: 100, servingUnit: "g" },
    { id: 175, name: "Raspberry", category: "fruits", calories: 52, protein: 1.2, carbs: 12, fat: 0.7, servingSize: 100, servingUnit: "g" },
    { id: 176, name: "Blackberry", category: "fruits", calories: 43, protein: 1.4, carbs: 10, fat: 0.5, servingSize: 100, servingUnit: "g" },
    { id: 177, name: "Cranberry", category: "fruits", calories: 46, protein: 0.4, carbs: 12, fat: 0.1, servingSize: 100, servingUnit: "g" },
    { id: 178, name: "Gooseberry", category: "fruits", calories: 44, protein: 0.9, carbs: 10, fat: 0.6, servingSize: 100, servingUnit: "g" },
    { id: 179, name: "Star Fruit", category: "fruits", calories: 31, protein: 1, carbs: 7, fat: 0.3, servingSize: 100, servingUnit: "g" },
    { id: 180, name: "Jackfruit", category: "fruits", calories: 95, protein: 1.7, carbs: 24, fat: 0.2, servingSize: 100, servingUnit: "g" },
    
    // Vegetables
    { id: 13, name: "Broccoli", category: "vegetables", calories: 34, protein: 2.8, carbs: 7, fat: 0.4, servingSize: 100, servingUnit: "g" },
    { id: 14, name: "Carrot", category: "vegetables", calories: 41, protein: 0.9, carbs: 10, fat: 0.2, servingSize: 100, servingUnit: "g" },
    { id: 15, name: "Spinach", category: "vegetables", calories: 23, protein: 2.9, carbs: 3.6, fat: 0.4, servingSize: 100, servingUnit: "g" },
    { id: 16, name: "Tomato", category: "vegetables", calories: 18, protein: 0.9, carbs: 3.9, fat: 0.2, servingSize: 100, servingUnit: "g" },
    { id: 17, name: "Cucumber", category: "vegetables", calories: 16, protein: 0.7, carbs: 3.6, fat: 0.1, servingSize: 100, servingUnit: "g" },
    { id: 18, name: "Bell Pepper", category: "vegetables", calories: 31, protein: 1, carbs: 6, fat: 0.3, servingSize: 100, servingUnit: "g" },
    { id: 19, name: "Lettuce", category: "vegetables", calories: 15, protein: 1.4, carbs: 2.9, fat: 0.2, servingSize: 100, servingUnit: "g" },
    { id: 20, name: "Cauliflower", category: "vegetables", calories: 25, protein: 2, carbs: 5, fat: 0.3, servingSize: 100, servingUnit: "g" },
    { id: 21, name: "Zucchini", category: "vegetables", calories: 17, protein: 1.2, carbs: 3.1, fat: 0.3, servingSize: 100, servingUnit: "g" },
    { id: 22, name: "Mushrooms", category: "vegetables", calories: 22, protein: 3.1, carbs: 3.3, fat: 0.3, servingSize: 100, servingUnit: "g" },
    { id: 23, name: "Onion", category: "vegetables", calories: 40, protein: 1.1, carbs: 9.3, fat: 0.1, servingSize: 100, servingUnit: "g" },
    { id: 24, name: "Garlic", category: "vegetables", calories: 149, protein: 6.4, carbs: 33, fat: 0.5, servingSize: 100, servingUnit: "g" },
    { id: 181, name: "Potato", category: "vegetables", calories: 77, protein: 2, carbs: 17, fat: 0.1, servingSize: 100, servingUnit: "g" },
    { id: 182, name: "Sweet Potato", category: "vegetables", calories: 86, protein: 1.6, carbs: 20, fat: 0.1, servingSize: 100, servingUnit: "g" },
    { id: 183, name: "Brussels Sprouts", category: "vegetables", calories: 43, protein: 3.4, carbs: 9, fat: 0.4, servingSize: 100, servingUnit: "g" },
    { id: 184, name: "Asparagus", category: "vegetables", calories: 20, protein: 2.2, carbs: 4, fat: 0.1, servingSize: 100, servingUnit: "g" },
    { id: 185, name: "Green Beans", category: "vegetables", calories: 31, protein: 1.8, carbs: 7, fat: 0.1, servingSize: 100, servingUnit: "g" },
    { id: 186, name: "Peas", category: "vegetables", calories: 81, protein: 5.4, carbs: 14, fat: 0.4, servingSize: 100, servingUnit: "g" },
    { id: 187, name: "Corn", category: "vegetables", calories: 96, protein: 3.4, carbs: 21, fat: 1.5, servingSize: 100, servingUnit: "g" },
    { id: 188, name: "Eggplant", category: "vegetables", calories: 35, protein: 1, carbs: 6, fat: 0.2, servingSize: 100, servingUnit: "g" },
    { id: 189, name: "Okra", category: "vegetables", calories: 33, protein: 2, carbs: 7, fat: 0.2, servingSize: 100, servingUnit: "g" },
    { id: 190, name: "Bitter Gourd", category: "vegetables", calories: 17, protein: 1, carbs: 3.7, fat: 0.2, servingSize: 100, servingUnit: "g" },
    { id: 191, name: "Bottle Gourd", category: "vegetables", calories: 15, protein: 0.6, carbs: 3.7, fat: 0.1, servingSize: 100, servingUnit: "g" },
    { id: 192, name: "Ridge Gourd", category: "vegetables", calories: 20, protein: 1.2, carbs: 4.2, fat: 0.1, servingSize: 100, servingUnit: "g" },
    { id: 193, name: "Pumpkin", category: "vegetables", calories: 26, protein: 1, carbs: 6, fat: 0.1, servingSize: 100, servingUnit: "g" },
    { id: 194, name: "Radish", category: "vegetables", calories: 16, protein: 0.7, carbs: 3.4, fat: 0.1, servingSize: 100, servingUnit: "g" },
    { id: 195, name: "Beetroot", category: "vegetables", calories: 43, protein: 1.6, carbs: 10, fat: 0.2, servingSize: 100, servingUnit: "g" },
    { id: 196, name: "Cabbage", category: "vegetables", calories: 25, protein: 1.3, carbs: 6, fat: 0.1, servingSize: 100, servingUnit: "g" },
    { id: 197, name: "Celery", category: "vegetables", calories: 16, protein: 0.8, carbs: 3, fat: 0.2, servingSize: 100, servingUnit: "g" },
    { id: 198, name: "Kale", category: "vegetables", calories: 35, protein: 2.9, carbs: 6, fat: 0.6, servingSize: 100, servingUnit: "g" },
    { id: 199, name: "Swiss Chard", category: "vegetables", calories: 19, protein: 1.8, carbs: 3.7, fat: 0.2, servingSize: 100, servingUnit: "g" },
    { id: 200, name: "Spring Onion", category: "vegetables", calories: 32, protein: 1.8, carbs: 7.3, fat: 0.2, servingSize: 100, servingUnit: "g" },
    { id: 201, name: "Leek", category: "vegetables", calories: 61, protein: 1.5, carbs: 14, fat: 0.3, servingSize: 100, servingUnit: "g" },
    { id: 202, name: "Artichoke", category: "vegetables", calories: 47, protein: 3.3, carbs: 10, fat: 0.2, servingSize: 100, servingUnit: "g" },
    
    // Proteins
    { id: 25, name: "Chicken Breast (cooked)", category: "proteins", calories: 165, protein: 31, carbs: 0, fat: 3.6, servingSize: 100, servingUnit: "g" },
    { id: 26, name: "Salmon (cooked)", category: "proteins", calories: 208, protein: 20, carbs: 0, fat: 13, servingSize: 100, servingUnit: "g" },
    { id: 27, name: "Tuna (canned)", category: "proteins", calories: 116, protein: 26, carbs: 0, fat: 0.8, servingSize: 100, servingUnit: "g" },
    { id: 28, name: "Egg", category: "proteins", calories: 155, protein: 13, carbs: 1.1, fat: 11, servingSize: 1, servingUnit: "egg" },
    { id: 161, name: "Egg Sandwich", category: "proteins", calories: 280, protein: 12, carbs: 28, fat: 14, servingSize: 1, servingUnit: "sandwich" },
    { id: 162, name: "Boiled Egg Whites", category: "proteins", calories: 52, protein: 11, carbs: 0.7, fat: 0.2, servingSize: 1, servingUnit: "egg white" },
    { id: 29, name: "Beef (lean, cooked)", category: "proteins", calories: 250, protein: 26, carbs: 0, fat: 15, servingSize: 100, servingUnit: "g" },
    { id: 30, name: "Turkey Breast (cooked)", category: "proteins", calories: 135, protein: 30, carbs: 0, fat: 1, servingSize: 100, servingUnit: "g" },
    { id: 31, name: "Shrimp (cooked)", category: "proteins", calories: 99, protein: 24, carbs: 0.2, fat: 0.3, servingSize: 100, servingUnit: "g" },
    { id: 32, name: "Tofu", category: "proteins", calories: 144, protein: 17, carbs: 3, fat: 9, servingSize: 100, servingUnit: "g" },
    { id: 33, name: "Lentils (cooked)", category: "proteins", calories: 116, protein: 9, carbs: 20, fat: 0.4, servingSize: 100, servingUnit: "g" },
    { id: 34, name: "Black Beans (cooked)", category: "proteins", calories: 132, protein: 8.9, carbs: 23, fat: 0.5, servingSize: 100, servingUnit: "g" },
    
    // Grains
    { id: 35, name: "White Rice (cooked)", category: "grains", calories: 130, protein: 2.7, carbs: 28, fat: 0.3, servingSize: 100, servingUnit: "g" },
    { id: 36, name: "Brown Rice (cooked)", category: "grains", calories: 112, protein: 2.6, carbs: 24, fat: 0.9, servingSize: 100, servingUnit: "g" },
    { id: 37, name: "Quinoa (cooked)", category: "grains", calories: 120, protein: 4.4, carbs: 21, fat: 1.9, servingSize: 100, servingUnit: "g" },
    { id: 38, name: "Oats (cooked)", category: "grains", calories: 68, protein: 2.4, carbs: 12, fat: 1.4, servingSize: 100, servingUnit: "g" },
    { id: 39, name: "Whole Wheat Bread", category: "grains", calories: 247, protein: 13, carbs: 41, fat: 3.4, servingSize: 1, servingUnit: "slice" },
    { id: 40, name: "Pasta (cooked)", category: "grains", calories: 131, protein: 5, carbs: 25, fat: 1.1, servingSize: 100, servingUnit: "g" },
    { id: 41, name: "Sweet Potato (cooked)", category: "grains", calories: 86, protein: 1.6, carbs: 20, fat: 0.1, servingSize: 100, servingUnit: "g" },
    { id: 42, name: "Corn (cooked)", category: "grains", calories: 96, protein: 3.4, carbs: 21, fat: 1.5, servingSize: 100, servingUnit: "g" },
    
    // Dairy
    { id: 43, name: "Milk (whole)", category: "dairy", calories: 61, protein: 3.2, carbs: 4.8, fat: 3.3, servingSize: 100, servingUnit: "ml" },
    { id: 44, name: "Milk (skim)", category: "dairy", calories: 35, protein: 3.4, carbs: 5, fat: 0.1, servingSize: 100, servingUnit: "ml" },
    { id: 45, name: "Greek Yogurt", category: "dairy", calories: 59, protein: 10, carbs: 3.6, fat: 0.4, servingSize: 100, servingUnit: "g" },
    { id: 46, name: "Cheddar Cheese", category: "dairy", calories: 403, protein: 25, carbs: 1.3, fat: 33, servingSize: 100, servingUnit: "g" },
    { id: 47, name: "Mozzarella Cheese", category: "dairy", calories: 280, protein: 28, carbs: 2.2, fat: 18, servingSize: 100, servingUnit: "g" },
    { id: 48, name: "Cottage Cheese", category: "dairy", calories: 98, protein: 11, carbs: 3.4, fat: 4.3, servingSize: 100, servingUnit: "g" },
    { id: 49, name: "Butter", category: "dairy", calories: 717, protein: 0.9, carbs: 0.1, fat: 81, servingSize: 100, servingUnit: "g" },
    { id: 50, name: "Cream Cheese", category: "dairy", calories: 342, protein: 6, carbs: 4.5, fat: 34, servingSize: 100, servingUnit: "g" },
    { id: 203, name: "Milk (2%)", category: "dairy", calories: 50, protein: 3.3, carbs: 4.8, fat: 1.9, servingSize: 100, servingUnit: "ml" },
    { id: 204, name: "Milk (1%)", category: "dairy", calories: 42, protein: 3.4, carbs: 4.9, fat: 1, servingSize: 100, servingUnit: "ml" },
    { id: 205, name: "Almond Milk (unsweetened)", category: "dairy", calories: 15, protein: 0.6, carbs: 0.6, fat: 1.1, servingSize: 100, servingUnit: "ml" },
    { id: 206, name: "Soy Milk (unsweetened)", category: "dairy", calories: 33, protein: 2.8, carbs: 1.7, fat: 1.8, servingSize: 100, servingUnit: "ml" },
    { id: 207, name: "Coconut Milk", category: "dairy", calories: 230, protein: 2.3, carbs: 3.4, fat: 24, servingSize: 100, servingUnit: "ml" },
    { id: 208, name: "Oat Milk (unsweetened)", category: "dairy", calories: 45, protein: 1, carbs: 6, fat: 1.5, servingSize: 100, servingUnit: "ml" },
    { id: 209, name: "Rice Milk", category: "dairy", calories: 47, protein: 0.3, carbs: 10, fat: 1, servingSize: 100, servingUnit: "ml" },
    { id: 210, name: "Buttermilk", category: "dairy", calories: 40, protein: 3.3, carbs: 4.8, fat: 1, servingSize: 100, servingUnit: "ml" },
    { id: 211, name: "Condensed Milk", category: "dairy", calories: 321, protein: 8, carbs: 54, fat: 9, servingSize: 100, servingUnit: "g" },
    { id: 212, name: "Evaporated Milk", category: "dairy", calories: 134, protein: 6.8, carbs: 10, fat: 7.6, servingSize: 100, servingUnit: "ml" },
    { id: 213, name: "Ice Cream (vanilla)", category: "dairy", calories: 207, protein: 3.5, carbs: 24, fat: 11, servingSize: 100, servingUnit: "g" },
    { id: 214, name: "Ice Cream (chocolate)", category: "dairy", calories: 216, protein: 3.8, carbs: 28, fat: 11, servingSize: 100, servingUnit: "g" },
    { id: 215, name: "Frozen Yogurt", category: "dairy", calories: 99, protein: 4, carbs: 22, fat: 0.7, servingSize: 100, servingUnit: "g" },
    { id: 216, name: "Paneer", category: "dairy", calories: 265, protein: 18, carbs: 3.4, fat: 20, servingSize: 100, servingUnit: "g" },
    
    // Snacks
    { id: 51, name: "Almonds", category: "snacks", calories: 579, protein: 21, carbs: 22, fat: 50, servingSize: 100, servingUnit: "g" },
    { id: 52, name: "Walnuts", category: "snacks", calories: 654, protein: 15, carbs: 14, fat: 65, servingSize: 100, servingUnit: "g" },
    { id: 53, name: "Peanuts", category: "snacks", calories: 567, protein: 26, carbs: 16, fat: 49, servingSize: 100, servingUnit: "g" },
    { id: 54, name: "Dark Chocolate", category: "snacks", calories: 598, protein: 7.8, carbs: 46, fat: 43, servingSize: 100, servingUnit: "g" },
    { id: 55, name: "Potato Chips", category: "snacks", calories: 536, protein: 7, carbs: 53, fat: 35, servingSize: 100, servingUnit: "g" },
    { id: 56, name: "Popcorn (air-popped)", category: "snacks", calories: 387, protein: 13, carbs: 78, fat: 4, servingSize: 100, servingUnit: "g" },
    { id: 57, name: "Granola Bar", category: "snacks", calories: 471, protein: 9, carbs: 64, fat: 19, servingSize: 1, servingUnit: "bar" },
    { id: 58, name: "Crackers", category: "snacks", calories: 488, protein: 8, carbs: 64, fat: 23, servingSize: 100, servingUnit: "g" },
    { id: 59, name: "Pretzels", category: "snacks", calories: 380, protein: 9, carbs: 79, fat: 3, servingSize: 100, servingUnit: "g" },
    { id: 60, name: "Dried Apricots", category: "snacks", calories: 241, protein: 3.5, carbs: 63, fat: 0.5, servingSize: 100, servingUnit: "g" },

    // Beverages - Fresh Juice
    { id: 217, name: "Orange Juice", category: "beverages", calories: 45, protein: 0.7, carbs: 10, fat: 0.2, servingSize: 100, servingUnit: "ml" },
    { id: 218, name: "Apple Juice", category: "beverages", calories: 46, protein: 0.1, carbs: 11, fat: 0.1, servingSize: 100, servingUnit: "ml" },
    { id: 219, name: "Grape Juice", category: "beverages", calories: 60, protein: 0.4, carbs: 15, fat: 0.1, servingSize: 100, servingUnit: "ml" },
    { id: 220, name: "Pineapple Juice", category: "beverages", calories: 53, protein: 0.4, carbs: 13, fat: 0.1, servingSize: 100, servingUnit: "ml" },
    { id: 221, name: "Mango Juice", category: "beverages", calories: 60, protein: 0.5, carbs: 15, fat: 0.1, servingSize: 100, servingUnit: "ml" },
    { id: 222, name: "Watermelon Juice", category: "beverages", calories: 30, protein: 0.4, carbs: 8, fat: 0.1, servingSize: 100, servingUnit: "ml" },
    { id: 223, name: "Pomegranate Juice", category: "beverages", calories: 54, protein: 0.2, carbs: 13, fat: 0.3, servingSize: 100, servingUnit: "ml" },
    { id: 224, name: "Carrot Juice", category: "beverages", calories: 41, protein: 0.9, carbs: 10, fat: 0.2, servingSize: 100, servingUnit: "ml" },
    { id: 225, name: "Beetroot Juice", category: "beverages", calories: 43, protein: 1.5, carbs: 10, fat: 0.2, servingSize: 100, servingUnit: "ml" },
    { id: 226, name: "Mixed Vegetable Juice", category: "beverages", calories: 35, protein: 1, carbs: 8, fat: 0.2, servingSize: 100, servingUnit: "ml" },
    { id: 227, name: "Sugarcane Juice", category: "beverages", calories: 83, protein: 0.2, carbs: 20, fat: 0, servingSize: 100, servingUnit: "ml" },
    { id: 228, name: "Coconut Water", category: "beverages", calories: 19, protein: 0.7, carbs: 3.7, fat: 0.2, servingSize: 100, servingUnit: "ml" },
    { id: 229, name: "Lemonade", category: "beverages", calories: 40, protein: 0.1, carbs: 10, fat: 0.1, servingSize: 100, servingUnit: "ml" },
    { id: 230, name: "Iced Tea (unsweetened)", category: "beverages", calories: 2, protein: 0, carbs: 0.5, fat: 0, servingSize: 100, servingUnit: "ml" },
    { id: 231, name: "Iced Tea (sweetened)", category: "beverages", calories: 40, protein: 0, carbs: 10, fat: 0, servingSize: 100, servingUnit: "ml" },

    // Beverages - Hot Beverages
    { id: 232, name: "Black Coffee", category: "beverages", calories: 2, protein: 0.3, carbs: 0, fat: 0, servingSize: 100, servingUnit: "ml" },
    { id: 233, name: "Coffee with Milk", category: "beverages", calories: 15, protein: 0.8, carbs: 1.5, fat: 0.6, servingSize: 100, servingUnit: "ml" },
    { id: 234, name: "Cappuccino", category: "beverages", calories: 40, protein: 2, carbs: 4, fat: 2, servingSize: 100, servingUnit: "ml" },
    { id: 235, name: "Latte", category: "beverages", calories: 55, protein: 2.5, carbs: 6, fat: 3, servingSize: 100, servingUnit: "ml" },
    { id: 236, name: "Espresso", category: "beverages", calories: 5, protein: 0.3, carbs: 0.5, fat: 0.1, servingSize: 30, servingUnit: "ml" },
    { id: 237, name: "Green Tea", category: "beverages", calories: 1, protein: 0, carbs: 0, fat: 0, servingSize: 100, servingUnit: "ml" },
    { id: 238, name: "Black Tea", category: "beverages", calories: 2, protein: 0, carbs: 0.5, fat: 0, servingSize: 100, servingUnit: "ml" },
    { id: 239, name: "Herbal Tea", category: "beverages", calories: 2, protein: 0, carbs: 0.5, fat: 0, servingSize: 100, servingUnit: "ml" },
    { id: 240, name: "Hot Chocolate", category: "beverages", calories: 80, protein: 2.5, carbs: 12, fat: 3, servingSize: 100, servingUnit: "ml" },

    // Beverages - Cocktails
    { id: 241, name: "Mojito", category: "beverages", calories: 170, protein: 0.2, carbs: 15, fat: 0, servingSize: 100, servingUnit: "ml" },
    { id: 242, name: "Margarita", category: "beverages", calories: 200, protein: 0.3, carbs: 13, fat: 0, servingSize: 100, servingUnit: "ml" },
    { id: 243, name: "Piña Colada", category: "beverages", calories: 245, protein: 0.5, carbs: 22, fat: 14, servingSize: 100, servingUnit: "ml" },
    { id: 244, name: "Mai Tai", category: "beverages", calories: 230, protein: 0.2, carbs: 20, fat: 0, servingSize: 100, servingUnit: "ml" },
    { id: 245, name: "Old Fashioned", category: "beverages", calories: 180, protein: 0, carbs: 10, fat: 0, servingSize: 100, servingUnit: "ml" },
    { id: 246, name: "Cosmopolitan", category: "beverages", calories: 150, protein: 0.1, carbs: 12, fat: 0, servingSize: 100, servingUnit: "ml" },
    { id: 247, name: "Martini", category: "beverages", calories: 125, protein: 0, carbs: 0.5, fat: 0, servingSize: 100, servingUnit: "ml" },
    { id: 248, name: "Daiquiri", category: "beverages", calories: 160, protein: 0.1, carbs: 14, fat: 0, servingSize: 100, servingUnit: "ml" },
    { id: 249, name: "Whiskey Sour", category: "beverages", calories: 160, protein: 0.3, carbs: 12, fat: 0, servingSize: 100, servingUnit: "ml" },

    // Beverages - Mocktails
    { id: 250, name: "Virgin Mojito", category: "beverages", calories: 70, protein: 0.2, carbs: 15, fat: 0, servingSize: 100, servingUnit: "ml" },
    { id: 251, name: "Virgin Piña Colada", category: "beverages", calories: 120, protein: 0.5, carbs: 18, fat: 4, servingSize: 100, servingUnit: "ml" },
    { id: 252, name: "Virgin Mary", category: "beverages", calories: 40, protein: 0.5, carbs: 8, fat: 0.2, servingSize: 100, servingUnit: "ml" },
    { id: 253, name: "Shirley Temple", category: "beverages", calories: 80, protein: 0, carbs: 18, fat: 0, servingSize: 100, servingUnit: "ml" },
    { id: 254, name: "Virgin Daiquiri", category: "beverages", calories: 90, protein: 0.2, carbs: 20, fat: 0, servingSize: 100, servingUnit: "ml" },
    { id: 255, name: "Mango Lassi", category: "beverages", calories: 100, protein: 3, carbs: 20, fat: 2, servingSize: 100, servingUnit: "ml" },
    { id: 256, name: "Rose Milk", category: "beverages", calories: 120, protein: 3, carbs: 18, fat: 4, servingSize: 100, servingUnit: "ml" },
    { id: 257, name: "Badam Milk", category: "beverages", calories: 140, protein: 4, carbs: 15, fat: 6, servingSize: 100, servingUnit: "ml" },

    // Beverages - Cold Drinks
    { id: 258, name: "Cola", category: "beverages", calories: 42, protein: 0, carbs: 10, fat: 0, servingSize: 100, servingUnit: "ml" },
    { id: 259, name: "Diet Cola", category: "beverages", calories: 0, protein: 0, carbs: 0, fat: 0, servingSize: 100, servingUnit: "ml" },
    { id: 260, name: "Sprite", category: "beverages", calories: 39, protein: 0, carbs: 10, fat: 0, servingSize: 100, servingUnit: "ml" },
    { id: 261, name: "Fanta", category: "beverages", calories: 39, protein: 0, carbs: 10, fat: 0, servingSize: 100, servingUnit: "ml" },
    { id: 262, name: "Energy Drink", category: "beverages", calories: 45, protein: 0, carbs: 11, fat: 0, servingSize: 100, servingUnit: "ml" },
    { id: 263, name: "Sports Drink", category: "beverages", calories: 20, protein: 0, carbs: 5, fat: 0, servingSize: 100, servingUnit: "ml" },
    { id: 264, name: "Soda Water", category: "beverages", calories: 0, protein: 0, carbs: 0, fat: 0, servingSize: 100, servingUnit: "ml" },
    { id: 265, name: "Tonic Water", category: "beverages", calories: 32, protein: 0, carbs: 8, fat: 0, servingSize: 100, servingUnit: "ml" },
    { id: 266, name: "Ginger Ale", category: "beverages", calories: 34, protein: 0, carbs: 9, fat: 0, servingSize: 100, servingUnit: "ml" },

    // Indian Cuisine - Breads
    { id: 61, name: "Roti/Chapati", category: "indian", calories: 104, protein: 3.5, carbs: 17, fat: 1.5, servingSize: 1, servingUnit: "roti" },
    { id: 62, name: "Naan", category: "indian", calories: 265, protein: 8, carbs: 45, fat: 5, servingSize: 1, servingUnit: "naan" },
    { id: 63, name: "Paratha (plain)", category: "indian", calories: 230, protein: 5, carbs: 30, fat: 10, servingSize: 1, servingUnit: "paratha" },
    { id: 64, name: "Paratha (aloo)", category: "indian", calories: 280, protein: 6, carbs: 35, fat: 13, servingSize: 1, servingUnit: "paratha" },
    { id: 65, name: "Puri", category: "indian", calories: 280, protein: 5, carbs: 35, fat: 13, servingSize: 1, servingUnit: "puri" },
    { id: 66, name: "Bhatura", category: "indian", calories: 300, protein: 7, carbs: 40, fat: 12, servingSize: 1, servingUnit: "bhatura" },
    { id: 67, name: "Kulcha", category: "indian", calories: 250, protein: 6, carbs: 38, fat: 9, servingSize: 1, servingUnit: "kulcha" },
    { id: 68, name: "Thepla", category: "indian", calories: 180, protein: 5, carbs: 25, fat: 7, servingSize: 1, servingUnit: "thepla" },

    // Indian Cuisine - Rice Dishes
    { id: 69, name: "Biryani (Chicken)", category: "indian", calories: 280, protein: 12, carbs: 35, fat: 10, servingSize: 1, servingUnit: "plate" },
    { id: 70, name: "Biryani (Vegetable)", category: "indian", calories: 200, protein: 5, carbs: 35, fat: 6, servingSize: 1, servingUnit: "plate" },
    { id: 71, name: "Biryani (Mutton)", category: "indian", calories: 320, protein: 15, carbs: 35, fat: 13, servingSize: 1, servingUnit: "plate" },
    { id: 72, name: "Pulao (Vegetable)", category: "indian", calories: 180, protein: 4, carbs: 32, fat: 5, servingSize: 1, servingUnit: "plate" },
    { id: 73, name: "Jeera Rice", category: "indian", calories: 150, protein: 3, carbs: 30, fat: 3, servingSize: 1, servingUnit: "plate" },
    { id: 74, name: "Lemon Rice", category: "indian", calories: 160, protein: 3, carbs: 32, fat: 3, servingSize: 1, servingUnit: "plate" },
    { id: 75, name: "Curd Rice", category: "indian", calories: 140, protein: 4, carbs: 28, fat: 3, servingSize: 1, servingUnit: "plate" },
    { id: 76, name: "Tamarind Rice", category: "indian", calories: 170, protein: 3, carbs: 33, fat: 4, servingSize: 1, servingUnit: "plate" },

    // Indian Cuisine - Curries & Gravies
    { id: 77, name: "Butter Chicken", category: "indian", calories: 280, protein: 18, carbs: 12, fat: 18, servingSize: 1, servingUnit: "bowl" },
    { id: 78, name: "Chicken Tikka Masala", category: "indian", calories: 260, protein: 20, carbs: 10, fat: 16, servingSize: 1, servingUnit: "bowl" },
    { id: 79, name: "Palak Paneer", category: "indian", calories: 200, protein: 12, carbs: 8, fat: 14, servingSize: 1, servingUnit: "bowl" },
    { id: 80, name: "Paneer Butter Masala", category: "indian", calories: 320, protein: 14, carbs: 12, fat: 23, servingSize: 1, servingUnit: "bowl" },
    { id: 81, name: "Shahi Paneer", category: "indian", calories: 300, protein: 13, carbs: 10, fat: 22, servingSize: 1, servingUnit: "bowl" },
    { id: 82, name: "Dal Makhani", category: "indian", calories: 180, protein: 9, carbs: 20, fat: 8, servingSize: 1, servingUnit: "bowl" },
    { id: 83, name: "Dal Tadka", category: "indian", calories: 150, protein: 8, carbs: 18, fat: 6, servingSize: 1, servingUnit: "bowl" },
    { id: 84, name: "Chole (Chana Masala)", category: "indian", calories: 160, protein: 8, carbs: 22, fat: 5, servingSize: 1, servingUnit: "bowl" },
    { id: 85, name: "Rajma", category: "indian", calories: 140, protein: 8, carbs: 20, fat: 4, servingSize: 1, servingUnit: "bowl" },
    { id: 86, name: "Aloo Gobi", category: "indian", calories: 120, protein: 3, carbs: 18, fat: 5, servingSize: 1, servingUnit: "bowl" },
    { id: 87, name: "Baingan Bharta", category: "indian", calories: 100, protein: 3, carbs: 12, fat: 5, servingSize: 1, servingUnit: "bowl" },
    { id: 88, name: "Bhindi Masala", category: "indian", calories: 110, protein: 3, carbs: 14, fat: 5, servingSize: 1, servingUnit: "bowl" },
    { id: 89, name: "Mutter Paneer", category: "indian", calories: 220, protein: 12, carbs: 10, fat: 15, servingSize: 1, servingUnit: "bowl" },
    { id: 90, name: "Kadai Paneer", category: "indian", calories: 240, protein: 13, carbs: 12, fat: 16, servingSize: 1, servingUnit: "bowl" },
    { id: 91, name: "Malai Kofta", category: "indian", calories: 280, protein: 10, carbs: 15, fat: 20, servingSize: 1, servingUnit: "bowl" },
    { id: 92, name: "Egg Curry", category: "indian", calories: 180, protein: 12, carbs: 8, fat: 12, servingSize: 1, servingUnit: "bowl" },
    { id: 93, name: "Fish Curry", category: "indian", calories: 160, protein: 15, carbs: 8, fat: 9, servingSize: 1, servingUnit: "bowl" },
    { id: 94, name: "Mutton Curry", category: "indian", calories: 300, protein: 18, carbs: 8, fat: 22, servingSize: 1, servingUnit: "bowl" },
    { id: 95, name: "Chicken Korma", category: "indian", calories: 270, protein: 16, carbs: 10, fat: 19, servingSize: 1, servingUnit: "bowl" },
    { id: 96, name: "Samosa", category: "indian", calories: 260, protein: 5, carbs: 30, fat: 14, servingSize: 1, servingUnit: "piece" },

    // Indian Cuisine - South Indian
    { id: 97, name: "Masala Dosa", category: "indian", calories: 250, protein: 6, carbs: 40, fat: 8, servingSize: 1, servingUnit: "dosa" },
    { id: 98, name: "Plain Dosa", category: "indian", calories: 170, protein: 4, carbs: 30, fat: 4, servingSize: 1, servingUnit: "dosa" },
    { id: 99, name: "Idli (2 pieces)", category: "indian", calories: 120, protein: 4, carbs: 24, fat: 1, servingSize: 2, servingUnit: "idli" },
    { id: 100, name: "Vada", category: "indian", calories: 280, protein: 6, carbs: 30, fat: 14, servingSize: 1, servingUnit: "vada" },
    { id: 101, name: "Uttapam", category: "indian", calories: 220, protein: 6, carbs: 35, fat: 7, servingSize: 1, servingUnit: "uttapam" },
    { id: 102, name: "Pongal", category: "indian", calories: 200, protein: 5, carbs: 35, fat: 5, servingSize: 1, servingUnit: "plate" },
    { id: 103, name: "Upma", category: "indian", calories: 180, protein: 4, carbs: 32, fat: 5, servingSize: 1, servingUnit: "plate" },
    { id: 104, name: "Sambar", category: "indian", calories: 80, protein: 4, carbs: 12, fat: 2, servingSize: 1, servingUnit: "bowl" },
    { id: 105, name: "Rasam", category: "indian", calories: 60, protein: 2, carbs: 10, fat: 1, servingSize: 1, servingUnit: "bowl" },
    { id: 106, name: "Coconut Chutney", category: "indian", calories: 180, protein: 2, carbs: 8, fat: 16, servingSize: 1, servingUnit: "serving" },
    { id: 107, name: "Appam", category: "indian", calories: 120, protein: 2, carbs: 25, fat: 2, servingSize: 1, servingUnit: "appam" },
    { id: 108, name: "Puttu", category: "indian", calories: 150, protein: 3, carbs: 30, fat: 2, servingSize: 1, servingUnit: "serving" },

    // Indian Cuisine - Snacks & Street Food
    { id: 109, name: "Pani Puri (6 pieces)", category: "indian", calories: 150, protein: 3, carbs: 25, fat: 5, servingSize: 6, servingUnit: "pieces" },
    { id: 110, name: "Pav Bhaji", category: "indian", calories: 280, protein: 6, carbs: 35, fat: 13, servingSize: 1, servingUnit: "plate" },
    { id: 111, name: "Vada Pav", category: "indian", calories: 290, protein: 6, carbs: 35, fat: 14, servingSize: 1, servingUnit: "vada pav" },
    { id: 112, name: "Dabeli", category: "indian", calories: 250, protein: 5, carbs: 32, fat: 12, servingSize: 1, servingUnit: "dabeli" },
    { id: 113, name: "Kachori", category: "indian", calories: 300, protein: 5, carbs: 35, fat: 16, servingSize: 1, servingUnit: "piece" },
    { id: 114, name: "Bhel Puri", category: "indian", calories: 180, protein: 4, carbs: 28, fat: 7, servingSize: 1, servingUnit: "plate" },
    { id: 115, name: "Sev Puri", category: "indian", calories: 200, protein: 4, carbs: 30, fat: 8, servingSize: 1, servingUnit: "plate" },
    { id: 116, name: "Dhokla", category: "indian", calories: 180, protein: 6, carbs: 28, fat: 5, servingSize: 1, servingUnit: "piece" },
    { id: 117, name: "Khandvi", category: "indian", calories: 160, protein: 5, carbs: 25, fat: 5, servingSize: 1, servingUnit: "piece" },
    { id: 118, name: "Muthia", category: "indian", calories: 150, protein: 5, carbs: 22, fat: 5, servingSize: 1, servingUnit: "piece" },
    { id: 119, name: "Pakora (Vegetable)", category: "indian", calories: 280, protein: 4, carbs: 25, fat: 18, servingSize: 1, servingUnit: "piece" },
    { id: 120, name: "Onion Pakora", category: "indian", calories: 300, protein: 3, carbs: 22, fat: 22, servingSize: 1, servingUnit: "piece" },
    { id: 121, name: "Aloo Tikki", category: "indian", calories: 250, protein: 3, carbs: 30, fat: 13, servingSize: 1, servingUnit: "piece" },
    { id: 122, name: "Chole Bhature", category: "indian", calories: 450, protein: 12, carbs: 55, fat: 20, servingSize: 1, servingUnit: "plate" },

    // Indian Cuisine - Sweets & Desserts
    { id: 123, name: "Gulab Jamun (2 pieces)", category: "indian", calories: 300, protein: 4, carbs: 45, fat: 12, servingSize: 2, servingUnit: "pieces" },
    { id: 124, name: "Jalebi (2 pieces)", category: "indian", calories: 280, protein: 2, carbs: 50, fat: 10, servingSize: 2, servingUnit: "pieces" },
    { id: 125, name: "Rasgulla (2 pieces)", category: "indian", calories: 180, protein: 4, carbs: 35, fat: 5, servingSize: 2, servingUnit: "pieces" },
    { id: 126, name: "Rasmalai (2 pieces)", category: "indian", calories: 280, protein: 6, carbs: 35, fat: 12, servingSize: 2, servingUnit: "pieces" },
    { id: 127, name: "Kheer (Rice Pudding)", category: "indian", calories: 200, protein: 4, carbs: 35, fat: 6, servingSize: 1, servingUnit: "bowl" },
    { id: 128, name: "Gajar Ka Halwa", category: "indian", calories: 250, protein: 3, carbs: 35, fat: 10, servingSize: 1, servingUnit: "bowl" },
    { id: 129, name: "Moong Dal Halwa", category: "indian", calories: 300, protein: 8, carbs: 35, fat: 14, servingSize: 1, servingUnit: "bowl" },
    { id: 130, name: "Soan Papdi", category: "indian", calories: 450, protein: 6, carbs: 55, fat: 22, servingSize: 1, servingUnit: "piece" },
    { id: 131, name: "Barfi", category: "indian", calories: 400, protein: 5, carbs: 50, fat: 20, servingSize: 1, servingUnit: "piece" },
    { id: 132, name: "Ladoo (Besan)", category: "indian", calories: 350, protein: 6, carbs: 40, fat: 18, servingSize: 1, servingUnit: "ladoo" },
    { id: 133, name: "Ladoo (Coconut)", category: "indian", calories: 320, protein: 4, carbs: 38, fat: 16, servingSize: 1, servingUnit: "ladoo" },
    { id: 134, name: "Kaju Katli", category: "indian", calories: 380, protein: 5, carbs: 45, fat: 20, servingSize: 1, servingUnit: "piece" },
    { id: 135, name: "Pedha", category: "indian", calories: 350, protein: 5, carbs: 45, fat: 16, servingSize: 1, servingUnit: "piece" },
    { id: 136, name: "Kalakand", category: "indian", calories: 320, protein: 6, carbs: 40, fat: 14, servingSize: 1, servingUnit: "piece" },
    { id: 137, name: "Shrikhand", category: "indian", calories: 250, protein: 8, carbs: 30, fat: 10, servingSize: 1, servingUnit: "bowl" },
    { id: 138, name: "Kulfi", category: "indian", calories: 280, protein: 5, carbs: 35, fat: 12, servingSize: 1, servingUnit: "piece" },

    // Indian Cuisine - Beverages
    { id: 139, name: "Masala Chai (with milk & sugar)", category: "indian", calories: 80, protein: 2, carbs: 12, fat: 3, servingSize: 1, servingUnit: "cup" },
    { id: 140, name: "Mango Lassi", category: "indian", calories: 150, protein: 4, carbs: 25, fat: 4, servingSize: 1, servingUnit: "glass" },
    { id: 141, name: "Sweet Lassi", category: "indian", calories: 120, protein: 4, carbs: 20, fat: 3, servingSize: 1, servingUnit: "glass" },
    { id: 142, name: "Salted Lassi", category: "indian", calories: 60, protein: 4, carbs: 8, fat: 3, servingSize: 1, servingUnit: "glass" },
    { id: 143, name: "Buttermilk (Chaas)", category: "indian", calories: 40, protein: 3, carbs: 5, fat: 2, servingSize: 1, servingUnit: "glass" },
    { id: 144, name: "Aam Panna", category: "indian", calories: 100, protein: 1, carbs: 22, fat: 2, servingSize: 1, servingUnit: "glass" },
    { id: 145, name: "Jaljeera", category: "indian", calories: 30, protein: 0.5, carbs: 7, fat: 0, servingSize: 1, servingUnit: "glass" },
    { id: 146, name: "Filter Coffee (with milk & sugar)", category: "indian", calories: 70, protein: 2, carbs: 10, fat: 3, servingSize: 1, servingUnit: "cup" },

    // Indian Cuisine - Other Popular Dishes
    { id: 147, name: "Thali (Vegetarian)", category: "indian", calories: 800, protein: 25, carbs: 120, fat: 25, servingSize: 1, servingUnit: "thali" },
    { id: 148, name: "Thali (Non-Vegetarian)", category: "indian", calories: 1000, protein: 40, carbs: 120, fat: 35, servingSize: 1, servingUnit: "thali" },
    { id: 149, name: "Khichdi", category: "indian", calories: 150, protein: 5, carbs: 28, fat: 3, servingSize: 1, servingUnit: "plate" },
    { id: 150, name: "Poha", category: "indian", calories: 180, protein: 4, carbs: 32, fat: 4, servingSize: 1, servingUnit: "plate" },
    { id: 151, name: "Sabudana Khichdi", category: "indian", calories: 200, protein: 2, carbs: 45, fat: 4, servingSize: 1, servingUnit: "plate" },
    { id: 152, name: "Pesarattu", category: "indian", calories: 160, protein: 8, carbs: 25, fat: 3, servingSize: 1, servingUnit: "pesarattu" },
    { id: 153, name: "Rava Dosa", category: "indian", calories: 190, protein: 4, carbs: 32, fat: 5, servingSize: 1, servingUnit: "dosa" },
    { id: 154, name: "Set Dosa", category: "indian", calories: 150, protein: 3, carbs: 28, fat: 3, servingSize: 1, servingUnit: "dosa" },
    { id: 155, name: "Neer Dosa", category: "indian", calories: 130, protein: 2, carbs: 28, fat: 1, servingSize: 1, servingUnit: "dosa" },
    { id: 156, name: "Pesarattu Upma", category: "indian", calories: 140, protein: 6, carbs: 22, fat: 3, servingSize: 1, servingUnit: "plate" },
    { id: 157, name: "Bisi Bele Bath", category: "indian", calories: 220, protein: 6, carbs: 38, fat: 6, servingSize: 1, servingUnit: "plate" },
    { id: 158, name: "Vangi Bath", category: "indian", calories: 180, protein: 4, carbs: 30, fat: 5, servingSize: 1, servingUnit: "plate" },
    { id: 159, name: "Tomato Bath", category: "indian", calories: 170, protein: 4, carbs: 28, fat: 5, servingSize: 1, servingUnit: "plate" },
    { id: 160, name: "Curd Rice with Pickle", category: "indian", calories: 180, protein: 5, carbs: 30, fat: 5, servingSize: 1, servingUnit: "plate" },
];
